name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # every day at midnight
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Generate snake game from GitHub contributions graph
        uses: Platane/snk@v3
        with:
          github_user_name: saiiexd
          outputs: |
            ./output/github-snake.svg
            ./output/github-snake-dark.svg?palette=github-dark

      - name: Push generated snake svg to the output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
